### ISSUE TITLE
IP leakage

### ISSUE THREAD

**Issue by dave9123** [BreadCatto/Server-Monitor#1]
@BreadCatto My IP is hella leaked cuz of you

**Comment by BreadCatto** [comment]
great

**Comment by dave9123** [comment]
Bro it's leaked to my whole server

**Comment by dave9123** [comment]
Make a choice to show IP or no in config.json or :gun:

**Comment by BreadCatto** [comment]
go to main.py and remove the ip part

**Comment by dave9123** [comment]
Just add config.json for it

**Comment by BreadCatto** [comment]
maybe
